from django.urls import path
from landing.views import (
    index,
    contact, 
    nok_page, 
    callback_request, 
    minstroy_page, 
    minstroy_list,
    exam,
    qualifications_list,
    attestation,
    TD,
    IO,
    NK,
    docs,
    preparation,
    safety,
    prep_request,
    threed
    )

urlpatterns = [
    path("callback/", callback_request, name="callback_request"),
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path("nok/", nok_page, name="nok"),
    path("minstroy/", minstroy_page, name="minstroy"),
    path('minstroy/list/', minstroy_list, name='list'),
    path('exam/', exam, name='exam'),
    path("qualifications/", qualifications_list, name="qualifications"),
    path("attestation/", attestation, name="attestation"),
    path("TD/", TD, name="TD"),
    path("IO/", IO, name="IO"),
    path("NK/", NK, name="NK"),
    path("docs/", docs, name="docs"),
    path("preparation/", preparation, name="preparation"),
    path("safety/", safety, name="safety"),
    path("threed/", threed, name="threed"),
    path("prep-request/", prep_request, name="prep_request"),
]