from django.urls import path
from landing.views import (
    index,
    contact, 
    nok_page, 
    callback_request, 
    # minstroy_page, 
    # minstroy_list,
    exam,
    qualifications_list,
    attestation,
    TD,
    IO,
    NK,
    docs,
    preparation,
    safety,
    prep_request,
    threed,
    noc_exam_print,
    noc_exam_upload,
    about_education_index,
    about_education_page,
    about_complaints,
    about_impartiality,
    about_gratitude,
    )

urlpatterns = [
    path("callback/", callback_request, name="callback_request"),
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path("about/education-info/", about_education_index, name="about_education"),
    path("about/education-info/<slug:slug>/", about_education_page, name="about_education_page"),
    path("about/complaints-and-appeals/", about_complaints, name="about_complaints"),
    path("about/impartiality-policy/", about_impartiality, name="about_impartiality"),
    path("about/gratitude/", about_gratitude, name="about_gratitude"),
    path("nok/", nok_page, name="nok"),
    # path("minstroy/", minstroy_page, name="minstroy"),
    # path('minstroy/list/', minstroy_list, name='list'),
    path('exam/', exam, name='exam'),
    path("qualifications/", qualifications_list, name="qualifications"),
    path("attestation/", attestation, name="attestation"),
    path("TD/", TD, name="TD"),
    path("IO/", IO, name="IO"),
    path("NK/", NK, name="NK"),
    path("docs/", docs, name="docs"),
    path("preparation/", preparation, name="preparation"),
    path("safety/", safety, name="safety"),
    path("threed/", threed, name="threed"),
    path("prep-request/", prep_request, name="prep_request"),

    path("noc-exam-print/", noc_exam_print, name="noc_exam_print"),
    path("noc-exam-upload/", noc_exam_upload, name="noc_exam_upload"),
]